package Tipo_clienteApp;


/**
* Tipo_clienteApp/Tipo_cliente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tipo_cliente.idl
* martes 7 de mayo de 2019 12:12:49 PM COT
*/

public interface Tipo_cliente extends Tipo_clienteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Tipo_cliente
