package Tipo_clienteApp;

/**
* Tipo_clienteApp/Tipo_clienteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tipo_cliente.idl
* martes 7 de mayo de 2019 12:12:49 PM COT
*/

public final class Tipo_clienteHolder implements org.omg.CORBA.portable.Streamable
{
  public Tipo_clienteApp.Tipo_cliente value = null;

  public Tipo_clienteHolder ()
  {
  }

  public Tipo_clienteHolder (Tipo_clienteApp.Tipo_cliente initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Tipo_clienteApp.Tipo_clienteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Tipo_clienteApp.Tipo_clienteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Tipo_clienteApp.Tipo_clienteHelper.type ();
  }

}
