package Tipo_pagoApp;


/**
* Tipo_pagoApp/Tipo_pagoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tipo_pago.idl
* martes 7 de mayo de 2019 12:19:12 PM COT
*/

abstract public class Tipo_pagoHelper
{
  private static String  _id = "IDL:Tipo_pagoApp/Tipo_pago:1.0";

  public static void insert (org.omg.CORBA.Any a, Tipo_pagoApp.Tipo_pago that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Tipo_pagoApp.Tipo_pago extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Tipo_pagoApp.Tipo_pagoHelper.id (), "Tipo_pago");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Tipo_pagoApp.Tipo_pago read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_Tipo_pagoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Tipo_pagoApp.Tipo_pago value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Tipo_pagoApp.Tipo_pago narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Tipo_pagoApp.Tipo_pago)
      return (Tipo_pagoApp.Tipo_pago)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Tipo_pagoApp._Tipo_pagoStub stub = new Tipo_pagoApp._Tipo_pagoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Tipo_pagoApp.Tipo_pago unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Tipo_pagoApp.Tipo_pago)
      return (Tipo_pagoApp.Tipo_pago)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Tipo_pagoApp._Tipo_pagoStub stub = new Tipo_pagoApp._Tipo_pagoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
