package Tipo_pagoApp;


/**
* Tipo_pagoApp/Tipo_pago.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tipo_pago.idl
* martes 7 de mayo de 2019 12:19:12 PM COT
*/

public interface Tipo_pago extends Tipo_pagoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Tipo_pago
