package Tipo_pagoApp;


/**
* Tipo_pagoApp/Tipo_pagoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tipo_pago.idl
* martes 7 de mayo de 2019 12:19:12 PM COT
*/

public interface Tipo_pagoOperations 
{
  boolean insertarTipo_pago (String descripcion, String estado, int id_banco);
  boolean actualizarTipo_pago (String descripcion, String estado, int id_banco);
  boolean eliminarTipo_pago (int id);
  void shutdown ();
} // interface Tipo_pagoOperations
