package ProveedoresApp;


/**
* ProveedoresApp/ProveedoresHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from proveedores.idl
* martes 7 de mayo de 2019 12:02:08 PM COT
*/

abstract public class ProveedoresHelper
{
  private static String  _id = "IDL:ProveedoresApp/Proveedores:1.0";

  public static void insert (org.omg.CORBA.Any a, ProveedoresApp.Proveedores that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProveedoresApp.Proveedores extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ProveedoresApp.ProveedoresHelper.id (), "Proveedores");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProveedoresApp.Proveedores read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ProveedoresStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProveedoresApp.Proveedores value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ProveedoresApp.Proveedores narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ProveedoresApp.Proveedores)
      return (ProveedoresApp.Proveedores)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ProveedoresApp._ProveedoresStub stub = new ProveedoresApp._ProveedoresStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ProveedoresApp.Proveedores unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ProveedoresApp.Proveedores)
      return (ProveedoresApp.Proveedores)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ProveedoresApp._ProveedoresStub stub = new ProveedoresApp._ProveedoresStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
