package ProveedoresApp;


/**
* ProveedoresApp/ProveedoresPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from proveedores.idl
* martes 7 de mayo de 2019 12:02:08 PM COT
*/

public abstract class ProveedoresPOA extends org.omg.PortableServer.Servant
 implements ProveedoresApp.ProveedoresOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarProveedores", new java.lang.Integer (0));
    _methods.put ("actualizarProveedor", new java.lang.Integer (1));
    _methods.put ("eliminarProveedor", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ProveedoresApp/Proveedores/insertarProveedores
       {
         int cedula = in.read_long ();
         String nombre = in.read_wstring ();
         String apellido = in.read_wstring ();
         String telefono = in.read_wstring ();
         int id_producto = in.read_long ();
         int id_marca = in.read_long ();
         int marca = in.read_long ();
         int precio_compra = in.read_long ();
         int precio_uno = in.read_long ();
         int precio_dos = in.read_long ();
         int precio_tres = in.read_long ();
         String fecha_compra = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarProveedores (cedula, nombre, apellido, telefono, id_producto, id_marca, marca, precio_compra, precio_uno, precio_dos, precio_tres, fecha_compra);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // ProveedoresApp/Proveedores/actualizarProveedor
       {
         int cedula = in.read_long ();
         String nombre = in.read_wstring ();
         String apellido = in.read_wstring ();
         String telefono = in.read_wstring ();
         int id_producto = in.read_long ();
         int id_marca = in.read_long ();
         int marca = in.read_long ();
         int precio_compra = in.read_long ();
         int precio_uno = in.read_long ();
         int precio_dos = in.read_long ();
         int precio_tres = in.read_long ();
         String fecha_compra = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarProveedor (cedula, nombre, apellido, telefono, id_producto, id_marca, marca, precio_compra, precio_uno, precio_dos, precio_tres, fecha_compra);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // ProveedoresApp/Proveedores/eliminarProveedor
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.eliminarProveedor (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // ProveedoresApp/Proveedores/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ProveedoresApp/Proveedores:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Proveedores _this() 
  {
    return ProveedoresHelper.narrow(
    super._this_object());
  }

  public Proveedores _this(org.omg.CORBA.ORB orb) 
  {
    return ProveedoresHelper.narrow(
    super._this_object(orb));
  }


} // class ProveedoresPOA
