package ProveedoresApp;


/**
* ProveedoresApp/ProveedoresOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from proveedores.idl
* martes 7 de mayo de 2019 12:02:08 PM COT
*/

public interface ProveedoresOperations 
{
  boolean insertarProveedores (int cedula, String nombre, String apellido, String telefono, int id_producto, int id_marca, int marca, int precio_compra, int precio_uno, int precio_dos, int precio_tres, String fecha_compra);
  boolean actualizarProveedor (int cedula, String nombre, String apellido, String telefono, int id_producto, int id_marca, int marca, int precio_compra, int precio_uno, int precio_dos, int precio_tres, String fecha_compra);
  boolean eliminarProveedor (int id);
  void shutdown ();
} // interface ProveedoresOperations
