package ProveedoresApp;


/**
* ProveedoresApp/Proveedores.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from proveedores.idl
* martes 7 de mayo de 2019 12:02:08 PM COT
*/

public interface Proveedores extends ProveedoresOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Proveedores
