package AdministradorApp;


/**
* AdministradorApp/AdministradorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from administrador.idl
* martes 7 de mayo de 2019 11:02:58 AM COT
*/

public interface AdministradorOperations 
{
  boolean insertarAdministrador (String nombre, int telefono);
  boolean actualizarAdministrador (String nombre, int telefono);
  boolean eliminarAdministrador (int id);
  void shutdown ();
} // interface AdministradorOperations
