package AdministradorApp;


/**
* AdministradorApp/AdministradorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from administrador.idl
* martes 7 de mayo de 2019 11:02:58 AM COT
*/

abstract public class AdministradorHelper
{
  private static String  _id = "IDL:AdministradorApp/Administrador:1.0";

  public static void insert (org.omg.CORBA.Any a, AdministradorApp.Administrador that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AdministradorApp.Administrador extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AdministradorApp.AdministradorHelper.id (), "Administrador");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AdministradorApp.Administrador read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AdministradorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AdministradorApp.Administrador value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static AdministradorApp.Administrador narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AdministradorApp.Administrador)
      return (AdministradorApp.Administrador)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AdministradorApp._AdministradorStub stub = new AdministradorApp._AdministradorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static AdministradorApp.Administrador unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AdministradorApp.Administrador)
      return (AdministradorApp.Administrador)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AdministradorApp._AdministradorStub stub = new AdministradorApp._AdministradorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
