package AdministradorApp;


/**
* AdministradorApp/Administrador.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from administrador.idl
* martes 7 de mayo de 2019 11:02:58 AM COT
*/

public interface Administrador extends AdministradorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Administrador
