package LoginApp;


/**
* LoginApp/LoginOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Login.idl
* lunes 6 de mayo de 2019 08:02:56 PM COT
*/

public interface LoginOperations 
{
  boolean insertarLogin (String usuario, String contrasena);
  boolean actualizarLogin (String usuario, String contrasena);
  boolean eliminarLogin (String usuario);
  void shutdown ();
} // interface LoginOperations
