package LoginApp;

/**
* LoginApp/LoginHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Login.idl
* lunes 6 de mayo de 2019 08:02:56 PM COT
*/

public final class LoginHolder implements org.omg.CORBA.portable.Streamable
{
  public LoginApp.Login value = null;

  public LoginHolder ()
  {
  }

  public LoginHolder (LoginApp.Login initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LoginApp.LoginHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LoginApp.LoginHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LoginApp.LoginHelper.type ();
  }

}
