package LoginApp;


/**
* LoginApp/Login.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Login.idl
* lunes 6 de mayo de 2019 08:02:56 PM COT
*/

public interface Login extends LoginOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Login
