package ProductoApp;


/**
* ProductoApp/productoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from producto.idl
* lunes 6 de mayo de 2019 07:58:55 PM COT
*/

public interface productoOperations 
{
  boolean insertarProducto (String nombre);
  boolean actualizarProducto (String nombre);
  boolean eliminarProducto (int id);
  void shutdown ();
} // interface productoOperations
