package ProductoApp;

/**
* ProductoApp/productoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from producto.idl
* lunes 6 de mayo de 2019 07:58:55 PM COT
*/

public final class productoHolder implements org.omg.CORBA.portable.Streamable
{
  public ProductoApp.producto value = null;

  public productoHolder ()
  {
  }

  public productoHolder (ProductoApp.producto initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProductoApp.productoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProductoApp.productoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProductoApp.productoHelper.type ();
  }

}
