package ProductoApp;


/**
* ProductoApp/producto.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from producto.idl
* lunes 6 de mayo de 2019 07:58:55 PM COT
*/

public interface producto extends productoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface producto
