package InformacionApp;

/**
* InformacionApp/InformacionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from informacion.idl
* martes 7 de mayo de 2019 11:37:59 AM COT
*/

public final class InformacionHolder implements org.omg.CORBA.portable.Streamable
{
  public InformacionApp.Informacion value = null;

  public InformacionHolder ()
  {
  }

  public InformacionHolder (InformacionApp.Informacion initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InformacionApp.InformacionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InformacionApp.InformacionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InformacionApp.InformacionHelper.type ();
  }

}
