package InformacionApp;


/**
* InformacionApp/Informacion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from informacion.idl
* martes 7 de mayo de 2019 11:37:59 AM COT
*/

public interface Informacion extends InformacionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Informacion
