package FacturacionApp;

/**
* FacturacionApp/FacturacionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from facturacion.idl
* martes 7 de mayo de 2019 11:34:30 AM COT
*/

public final class FacturacionHolder implements org.omg.CORBA.portable.Streamable
{
  public FacturacionApp.Facturacion value = null;

  public FacturacionHolder ()
  {
  }

  public FacturacionHolder (FacturacionApp.Facturacion initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FacturacionApp.FacturacionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FacturacionApp.FacturacionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FacturacionApp.FacturacionHelper.type ();
  }

}
