package FacturacionApp;


/**
* FacturacionApp/FacturacionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from facturacion.idl
* martes 7 de mayo de 2019 11:34:30 AM COT
*/

public abstract class FacturacionPOA extends org.omg.PortableServer.Servant
 implements FacturacionApp.FacturacionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarFacturacion", new java.lang.Integer (0));
    _methods.put ("actualizarFacturacion", new java.lang.Integer (1));
    _methods.put ("eliminarFacturacion", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FacturacionApp/Facturacion/insertarFacturacion
       {
         String fecha_venta = in.read_wstring ();
         int id_cliente = in.read_long ();
         int id_producto = in.read_long ();
         int cantidad = in.read_long ();
         int precio_unidad = in.read_long ();
         int precio_sin_iva = in.read_long ();
         int precio_con_iva = in.read_long ();
         int id_tipo_pago = in.read_long ();
         int id_local = in.read_long ();
         boolean $result = false;
         $result = this.insertarFacturacion (fecha_venta, id_cliente, id_producto, cantidad, precio_unidad, precio_sin_iva, precio_con_iva, id_tipo_pago, id_local);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // FacturacionApp/Facturacion/actualizarFacturacion
       {
         String fecha_venta = in.read_wstring ();
         int id_cliente = in.read_long ();
         int id_producto = in.read_long ();
         int cantidad = in.read_long ();
         int precio_unidad = in.read_long ();
         int precio_sin_iva = in.read_long ();
         int precio_con_iva = in.read_long ();
         int id_tipo_pago = in.read_long ();
         int id_local = in.read_long ();
         boolean $result = false;
         $result = this.actualizarFacturacion (fecha_venta, id_cliente, id_producto, cantidad, precio_unidad, precio_sin_iva, precio_con_iva, id_tipo_pago, id_local);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // FacturacionApp/Facturacion/eliminarFacturacion
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.eliminarFacturacion (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // FacturacionApp/Facturacion/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FacturacionApp/Facturacion:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Facturacion _this() 
  {
    return FacturacionHelper.narrow(
    super._this_object());
  }

  public Facturacion _this(org.omg.CORBA.ORB orb) 
  {
    return FacturacionHelper.narrow(
    super._this_object(orb));
  }


} // class FacturacionPOA
