package FacturacionApp;


/**
* FacturacionApp/Facturacion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from facturacion.idl
* martes 7 de mayo de 2019 11:34:30 AM COT
*/

public interface Facturacion extends FacturacionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Facturacion
