package MarcaApp;


/**
* MarcaApp/MarcaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from marca.idl
* martes 7 de mayo de 2019 11:48:57 AM COT
*/

public interface MarcaOperations 
{
  boolean insertarMarca (String Marca);
  boolean actualizarMarca (String marca);
  boolean eliminarMarca (int id);
  void shutdown ();
} // interface MarcaOperations
