package MarcaApp;


/**
* MarcaApp/MarcaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from marca.idl
* martes 7 de mayo de 2019 11:48:57 AM COT
*/

public abstract class MarcaPOA extends org.omg.PortableServer.Servant
 implements MarcaApp.MarcaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarMarca", new java.lang.Integer (0));
    _methods.put ("actualizarMarca", new java.lang.Integer (1));
    _methods.put ("eliminarMarca", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MarcaApp/Marca/insertarMarca
       {
         String Marca = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarMarca (Marca);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // MarcaApp/Marca/actualizarMarca
       {
         String marca = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarMarca (marca);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // MarcaApp/Marca/eliminarMarca
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.eliminarMarca (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // MarcaApp/Marca/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MarcaApp/Marca:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Marca _this() 
  {
    return MarcaHelper.narrow(
    super._this_object());
  }

  public Marca _this(org.omg.CORBA.ORB orb) 
  {
    return MarcaHelper.narrow(
    super._this_object(orb));
  }


} // class MarcaPOA
