package MarcaApp;


/**
* MarcaApp/Marca.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from marca.idl
* martes 7 de mayo de 2019 11:48:57 AM COT
*/

public interface Marca extends MarcaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Marca
