package MarcaApp;

/**
* MarcaApp/MarcaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from marca.idl
* martes 7 de mayo de 2019 11:48:57 AM COT
*/

public final class MarcaHolder implements org.omg.CORBA.portable.Streamable
{
  public MarcaApp.Marca value = null;

  public MarcaHolder ()
  {
  }

  public MarcaHolder (MarcaApp.Marca initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MarcaApp.MarcaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MarcaApp.MarcaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MarcaApp.MarcaHelper.type ();
  }

}
