package SueldoApp;


/**
* SueldoApp/SueldoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sueldo.idl
* martes 7 de mayo de 2019 12:07:06 PM COT
*/

public abstract class SueldoPOA extends org.omg.PortableServer.Servant
 implements SueldoApp.SueldoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarSueldo", new java.lang.Integer (0));
    _methods.put ("actualizarSueldo", new java.lang.Integer (1));
    _methods.put ("eliminarSueldo", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // SueldoApp/Sueldo/insertarSueldo
       {
         int id_trabajador = in.read_long ();
         int sueldo = in.read_long ();
         String estado = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarSueldo (id_trabajador, sueldo, estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // SueldoApp/Sueldo/actualizarSueldo
       {
         int id_trabajador = in.read_long ();
         int sueldo = in.read_long ();
         String estado = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarSueldo (id_trabajador, sueldo, estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // SueldoApp/Sueldo/eliminarSueldo
       {
         int id_trabajador = in.read_long ();
         boolean $result = false;
         $result = this.eliminarSueldo (id_trabajador);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // SueldoApp/Sueldo/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SueldoApp/Sueldo:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Sueldo _this() 
  {
    return SueldoHelper.narrow(
    super._this_object());
  }

  public Sueldo _this(org.omg.CORBA.ORB orb) 
  {
    return SueldoHelper.narrow(
    super._this_object(orb));
  }


} // class SueldoPOA
