package SueldoApp;


/**
* SueldoApp/SueldoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sueldo.idl
* martes 7 de mayo de 2019 12:07:07 PM COT
*/

public interface SueldoOperations 
{
  boolean insertarSueldo (int id_trabajador, int sueldo, String estado);
  boolean actualizarSueldo (int id_trabajador, int sueldo, String estado);
  boolean eliminarSueldo (int id_trabajador);
  void shutdown ();
} // interface SueldoOperations
