package SueldoApp;


/**
* SueldoApp/SueldoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sueldo.idl
* martes 7 de mayo de 2019 12:07:07 PM COT
*/

abstract public class SueldoHelper
{
  private static String  _id = "IDL:SueldoApp/Sueldo:1.0";

  public static void insert (org.omg.CORBA.Any a, SueldoApp.Sueldo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static SueldoApp.Sueldo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (SueldoApp.SueldoHelper.id (), "Sueldo");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static SueldoApp.Sueldo read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SueldoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, SueldoApp.Sueldo value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static SueldoApp.Sueldo narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SueldoApp.Sueldo)
      return (SueldoApp.Sueldo)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SueldoApp._SueldoStub stub = new SueldoApp._SueldoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static SueldoApp.Sueldo unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SueldoApp.Sueldo)
      return (SueldoApp.Sueldo)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SueldoApp._SueldoStub stub = new SueldoApp._SueldoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
