package SueldoApp;

/**
* SueldoApp/SueldoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sueldo.idl
* martes 7 de mayo de 2019 12:07:07 PM COT
*/

public final class SueldoHolder implements org.omg.CORBA.portable.Streamable
{
  public SueldoApp.Sueldo value = null;

  public SueldoHolder ()
  {
  }

  public SueldoHolder (SueldoApp.Sueldo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SueldoApp.SueldoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SueldoApp.SueldoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SueldoApp.SueldoHelper.type ();
  }

}
