package PendienteApp;


/**
* PendienteApp/PendientePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from pendiente.idl
* martes 7 de mayo de 2019 11:54:20 AM COT
*/

public abstract class PendientePOA extends org.omg.PortableServer.Servant
 implements PendienteApp.PendienteOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarPendiente", new java.lang.Integer (0));
    _methods.put ("actualizarPendiente", new java.lang.Integer (1));
    _methods.put ("eliminarPendiente", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // PendienteApp/Pendiente/insertarPendiente
       {
         String descripcion = in.read_wstring ();
         int id_facturacion = in.read_long ();
         boolean $result = false;
         $result = this.insertarPendiente (descripcion, id_facturacion);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // PendienteApp/Pendiente/actualizarPendiente
       {
         String descripcion = in.read_wstring ();
         int id_facturacion = in.read_long ();
         boolean $result = false;
         $result = this.actualizarPendiente (descripcion, id_facturacion);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // PendienteApp/Pendiente/eliminarPendiente
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.eliminarPendiente (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // PendienteApp/Pendiente/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PendienteApp/Pendiente:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Pendiente _this() 
  {
    return PendienteHelper.narrow(
    super._this_object());
  }

  public Pendiente _this(org.omg.CORBA.ORB orb) 
  {
    return PendienteHelper.narrow(
    super._this_object(orb));
  }


} // class PendientePOA
