package PendienteApp;


/**
* PendienteApp/Pendiente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from pendiente.idl
* martes 7 de mayo de 2019 11:54:20 AM COT
*/

public interface Pendiente extends PendienteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Pendiente
