package PendienteApp;


/**
* PendienteApp/PendienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from pendiente.idl
* martes 7 de mayo de 2019 11:54:20 AM COT
*/

public interface PendienteOperations 
{
  boolean insertarPendiente (String descripcion, int id_facturacion);
  boolean actualizarPendiente (String descripcion, int id_facturacion);
  boolean eliminarPendiente (int id);
  void shutdown ();
} // interface PendienteOperations
