package TrabajadoresApp;

/**
* TrabajadoresApp/TrabajadoresHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from trabajadores.idl
* martes 7 de mayo de 2019 12:23:09 PM COT
*/

public final class TrabajadoresHolder implements org.omg.CORBA.portable.Streamable
{
  public TrabajadoresApp.Trabajadores value = null;

  public TrabajadoresHolder ()
  {
  }

  public TrabajadoresHolder (TrabajadoresApp.Trabajadores initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TrabajadoresApp.TrabajadoresHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TrabajadoresApp.TrabajadoresHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TrabajadoresApp.TrabajadoresHelper.type ();
  }

}
