package TrabajadoresApp;


/**
* TrabajadoresApp/Trabajadores.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from trabajadores.idl
* martes 7 de mayo de 2019 12:23:09 PM COT
*/

public interface Trabajadores extends TrabajadoresOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Trabajadores
