package TrabajadoresApp;


/**
* TrabajadoresApp/TrabajadoresOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from trabajadores.idl
* martes 7 de mayo de 2019 12:23:09 PM COT
*/

public interface TrabajadoresOperations 
{
  boolean insertarTrabajadores (String nombre, String estado, int id_local);
  boolean actualizarTrabajadores (String nombre, String estado, int id_local);
  boolean eliminarTrabajadores (int id);
  void shutdown ();
} // interface TrabajadoresOperations
