package ClienteApp;


/**
* ClienteApp/ClienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cliente.idl
* martes 7 de mayo de 2019 11:16:11 AM COT
*/

public interface ClienteOperations 
{
  boolean insertarCliente (String nombre, String apellido, String tipo_cedula, int cedula, int id_tipo_cliente);
  boolean actualizarCliente (String nombre, String apellido, String tipo_cedula, int cedula, int id_tipo_cliente);
  boolean eliminarCliente (int id);
  void shutdown ();
} // interface ClienteOperations
