package ClienteApp;


/**
* ClienteApp/ClientePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cliente.idl
* martes 7 de mayo de 2019 11:16:11 AM COT
*/

public abstract class ClientePOA extends org.omg.PortableServer.Servant
 implements ClienteApp.ClienteOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarCliente", new java.lang.Integer (0));
    _methods.put ("actualizarCliente", new java.lang.Integer (1));
    _methods.put ("eliminarCliente", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ClienteApp/Cliente/insertarCliente
       {
         String nombre = in.read_wstring ();
         String apellido = in.read_wstring ();
         String tipo_cedula = in.read_wstring ();
         int cedula = in.read_long ();
         int id_tipo_cliente = in.read_long ();
         boolean $result = false;
         $result = this.insertarCliente (nombre, apellido, tipo_cedula, cedula, id_tipo_cliente);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // ClienteApp/Cliente/actualizarCliente
       {
         String nombre = in.read_wstring ();
         String apellido = in.read_wstring ();
         String tipo_cedula = in.read_wstring ();
         int cedula = in.read_long ();
         int id_tipo_cliente = in.read_long ();
         boolean $result = false;
         $result = this.actualizarCliente (nombre, apellido, tipo_cedula, cedula, id_tipo_cliente);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // ClienteApp/Cliente/eliminarCliente
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.eliminarCliente (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // ClienteApp/Cliente/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ClienteApp/Cliente:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Cliente _this() 
  {
    return ClienteHelper.narrow(
    super._this_object());
  }

  public Cliente _this(org.omg.CORBA.ORB orb) 
  {
    return ClienteHelper.narrow(
    super._this_object(orb));
  }


} // class ClientePOA
