package ClienteApp;


/**
* ClienteApp/Cliente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cliente.idl
* martes 7 de mayo de 2019 11:16:11 AM COT
*/

public interface Cliente extends ClienteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Cliente
