module login{
    interface login{
            boolean insertarLogin(in wstring usuario, in wstring contraseña);
          boolean actualizarLogin(in wstring usuario, in wstring contraseña);
            boolean eliminarLogin(in wstring usuario);
        oneway void shutdown();
    };
};
