package Local1App;


/**
* Local1App/Local1.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from local1.idl
* martes 7 de mayo de 2019 11:44:07 AM COT
*/

public interface Local1 extends Local1Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Local1
