package Local1App;


/**
* Local1App/Local1Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from local1.idl
* martes 7 de mayo de 2019 11:44:07 AM COT
*/

public interface Local1Operations 
{
  boolean insertarLocal (String nombre, String direccion, int id_administrador);
  boolean actualizarLocal (String nombre, String direccion, int id_administrador);
  boolean eliminarLocal (int id);
  void shutdown ();
} // interface Local1Operations
