package Local1App;


/**
* Local1App/Local1Helper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from local1.idl
* martes 7 de mayo de 2019 11:44:07 AM COT
*/

abstract public class Local1Helper
{
  private static String  _id = "IDL:Local1App/Local1:1.0";

  public static void insert (org.omg.CORBA.Any a, Local1App.Local1 that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Local1App.Local1 extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Local1App.Local1Helper.id (), "Local1");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Local1App.Local1 read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_Local1Stub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Local1App.Local1 value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Local1App.Local1 narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Local1App.Local1)
      return (Local1App.Local1)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Local1App._Local1Stub stub = new Local1App._Local1Stub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Local1App.Local1 unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Local1App.Local1)
      return (Local1App.Local1)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Local1App._Local1Stub stub = new Local1App._Local1Stub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
