package Local1App;

/**
* Local1App/Local1Holder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from local1.idl
* martes 7 de mayo de 2019 11:44:07 AM COT
*/

public final class Local1Holder implements org.omg.CORBA.portable.Streamable
{
  public Local1App.Local1 value = null;

  public Local1Holder ()
  {
  }

  public Local1Holder (Local1App.Local1 initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Local1App.Local1Helper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Local1App.Local1Helper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Local1App.Local1Helper.type ();
  }

}
