package Local1App;


/**
* Local1App/Local1POA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from local1.idl
* martes 7 de mayo de 2019 11:44:07 AM COT
*/

public abstract class Local1POA extends org.omg.PortableServer.Servant
 implements Local1App.Local1Operations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarLocal", new java.lang.Integer (0));
    _methods.put ("actualizarLocal", new java.lang.Integer (1));
    _methods.put ("eliminarLocal", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Local1App/Local1/insertarLocal
       {
         String nombre = in.read_wstring ();
         String direccion = in.read_wstring ();
         int id_administrador = in.read_long ();
         boolean $result = false;
         $result = this.insertarLocal (nombre, direccion, id_administrador);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Local1App/Local1/actualizarLocal
       {
         String nombre = in.read_wstring ();
         String direccion = in.read_wstring ();
         int id_administrador = in.read_long ();
         boolean $result = false;
         $result = this.actualizarLocal (nombre, direccion, id_administrador);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Local1App/Local1/eliminarLocal
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.eliminarLocal (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Local1App/Local1/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Local1App/Local1:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Local1 _this() 
  {
    return Local1Helper.narrow(
    super._this_object());
  }

  public Local1 _this(org.omg.CORBA.ORB orb) 
  {
    return Local1Helper.narrow(
    super._this_object(orb));
  }


} // class Local1POA
