package BancoApp;


/**
* BancoApp/Banco.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banco.idl
* martes 7 de mayo de 2019 11:06:32 AM COT
*/

public interface Banco extends BancoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Banco
